# Generated by Django 4.1.4 on 2023-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_alter_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
