# Generated by Django 4.1.4 on 2023-06-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
