# Generated by Django 4.1.4 on 2023-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(null=True, to='elearn.course'),
        ),
    ]
