# Generated by Django 4.1.4 on 2023-06-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0011_remove_userprofile_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrolled_courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elearn.course'),
        ),
    ]
