# Generated by Django 4.1.4 on 2023-06-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0013_remove_userprofile_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(to='elearn.course'),
        ),
    ]
