# Generated by Django 4.1.4 on 2023-06-23 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0014_alter_userprofile_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ratings',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
